# Generated by Django 5.0.6 on 2025-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
