# Generated by Django 5.0.6 on 2025-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredients_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
