# Generated by Django 5.0.6 on 2025-02-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredients_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
