# Generated by Django 5.0.6 on 2025-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredients_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/'),
        ),
    ]
