"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.
"""

from pathlib import Path
import os

# 📌 Configuración de Base de Proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# 📌 Clave Secreta (⚠️ No compartir en producción)
SECRET_KEY = 'django-insecure-k_obp!ppezl+u9ct9(aqre(pa2l8ags06t@ut^u=g&m)m!kcyw'

# 📌 Modo Debug (⚠️ Desactivar en producción)
DEBUG = True

# 📌 Hosts Permitidos
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# 📌 Aplicaciones Instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 📌 Dependencias de terceros
    'rest_framework',
    "corsheaders",

    # 📌 Aplicaciones Personalizadas
    'core',
    'ingredients',
    'product'
]

# 📌 Middlewares
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 📌 Configuración de URLs
ROOT_URLCONF = 'backend.urls'

# 📌 Configuración de Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 📌 Configuración de WSGI
WSGI_APPLICATION = 'backend.wsgi.application'

# 📌 Configuración de Base de Datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 📌 Configuración de Archivos Media
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 📌 Configuración de Archivos Estáticos
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# 📌 Validaciones de Contraseña
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 📌 Configuración de Idioma y Zona Horaria
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# 📌 Configuración de CORS (Para conectar con Next.js)
CORS_ALLOW_ALL_ORIGINS = True  # 🚀 Habilita CORS para todas las conexiones (desactivar en producción)

# Si deseas permitir solo dominios específicos, usa esta configuración en vez de `CORS_ALLOW_ALL_ORIGINS = True`
# CORS_ALLOWED_ORIGINS = [
#     "http://192.168.100.84:3000",
#     "http://localhost:3000",
# ]

# 📌 Configuración del Tipo de Clave Primaria por Defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
